---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: odh-subscription
spec:
  channel: stable
  installPlanApproval: Automatic
  name: opendatahub-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: opendatahub-operator.v1.1.0
