apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/argoproj/argo-workflows/manifests/cluster-install/argo-server-rbac?ref=v2.12.5

patchesStrategicMerge:
  - ns_patch.yaml