apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    opendatahub.io/notebook-image-desc: Image with jupyter notebooks for image detection
      exploration
    opendatahub.io/notebook-image-name: Image Detection Notebook Image
    opendatahub.io/notebook-image-url: https://github.com/aicoe-aiops/pet-image-detection
  labels:
    opendatahub.io/notebook-image: "true"
  name: pet-image-detection
  namespace: opf-jupyterhub-stage
spec:
  lookupPolicy:
    local: true
  tags:
  - annotations:
      openshift.io/imported-from: quay.io/aicoe/pet-image-detection
    from:
      kind: DockerImage
      name: quay.io/aicoe/pet-image-detection:latest
    importPolicy:
      scheduled: true
    name: latest
