apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kfdefs
spec:
  destination:
    name: in-cluster
    namespace: openshift-operators
  project: default
  source:
    path: kfdefs
    repoURL: https://github.com/HumairAK/devconf-2021.git
    targetRevision: HEAD
#### Uncomment Below to enable AutoSync
#  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
#    syncOptions:
#      - Validate=false
