apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - https://github.com/operate-first/apps/argocd/overlays/dev

patchesStrategicMerge:
  - argocd-cm_patch.yaml