kind: Secret
apiVersion: v1
metadata:
    name: my-secret
stringData:
    mypassword: ENC[AES256_GCM,data:3fRc945Pau6NTXDWdYe/KtORhsGo,iv:V921IhZWLn42zhoF0SzIKmChTxUi7VdT7bs73xJ+O0M=,tag:4/2gif3yCF8320uMr7x0lQ==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-08-22T16:48:47Z'
    mac: ENC[AES256_GCM,data:2lmFdXAvo/rLeaKLbLtLdVtih6n0YrACA3Ekc1iHpLxd2roM3vFO6tlOYKbmK2y/kNMI/EO1pOnYLK/D33/uxiN/HLnqQixzPajEmjR0ZIS1BTKNZQ6zkH8WdsqYXwTeUUObjv7LbmbxCrm4s6U0ydJfGf0+st18ZbAMBRoyMAQ=,iv:6MbZT0iDFnlLcYe22JtPy0QeCRe6fPplPcoF+2JMEvY=,tag:MEiKHSB+Or6SrW5ok+QFTA==,type:str]
    pgp:
    -   created_at: '2021-08-22T16:48:46Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMAw9LuDDzyAuHAQgAq9Ca1yLV4+kXatri+SMtaYNEJYKv3uUdaVRDRYBw8E98
            od9VNWsRubHLp2nfJh1tHuxywxOGwxEqO+vsDWU1SzWFd5pueH1AkJA2/+jZkR9F
            kXSNL/BEDrFzBDia9wWiCReIa589eyFLNfqtJCM9Y3wZ5o3C8+o2H96BoT3NLiUQ
            GLPUCJE0wxzMtv3ya2tJ/++l1JFrW6JH492kavsxyLLsTg9UNbqUx8yu6agVQPfh
            9ef9dCfUBuHqpbF6WSocwiSwOx3U0ya/NY1pX6KPHaKb6lyp90Ar9O623nZiaRJC
            U350C0kUv49kp+LK93ApFbaZ2s/EYxuXbAJNtMLUydJeAXEIdz4XmtWdTrmxbz7F
            fzOb668MTwseepZmFrbrMqnp5pjofE8t8b/TW1gijHd6BGD02Ap2vteY2k8+rjhY
            0y5NFWD3orBmdiGpeWTqmQgvWCpOysUU6FEBABMkfQ==
            =C2iL
            -----END PGP MESSAGE-----
        fp: 4A3823FD0F174F3AC0F945104AFCDBF2C2654B2F
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
