# To run this example, first create the secret by running:
# kubectl create secret generic my-secret --from-literal=mypassword=S00perS3cretPa55word
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: secret-example
spec:
  entrypoint: whalesay
  volumes:
    - name: my-secret-vol
      secret:
        secretName: my-secret
  templates:
    - name: whalesay
      container:
        image: quay.io/hukhan/alpine:3.7
        command: [sh, -c]
        args: ['
        echo "secret from env: $MYSECRETPASSWORD";
        echo "secret from file: `cat /secret/mountpath/mypassword`"
      ']
        env:
          - name: MYSECRETPASSWORD
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: mypassword
        volumeMounts:
          - name: my-secret-vol
            mountPath: "/secret/mountpath"
